import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import ReactQuery from "@/app/ReactQuery";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <ReactQuery>
            <div className="container mx-auto max-w-2xl border-[1px] border-gray-500">
                {children}
            </div>
        </ReactQuery>
        </body>
        </html>
    )
}
